/// Power Query M mirror of Risk_Updates with an added drillthrough_risk_id column that points at the SAME risk (self-referential), enabling a parallel active M:1 relationship to Risk_Register. Workaround for the production-side Risk_Updates -> Risk_Register filter propagation issue (the existing direct M:1 relationship on Risk_Updates.risk_id does not propagate filter context in the Service, despite the on-disk relationships.tmdl being identical to Risk_Updates_AsNext's working relationship). Page 3 UpdatesHistory tableEx binds to this table instead of Risk_Updates so the drillthrough page filter on Risk_Register[risk_id] propagates correctly through this new relationship.
table Risk_Updates_AsCurrent
	lineageTag: aa1b2c3d-0001-4000-8000-000000000001

	column update_id
		dataType: string
		lineageTag: aa1b2c3d-0001-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: update_id

		annotation SummarizationSetBy = User

	column risk_id
		dataType: string
		lineageTag: aa1b2c3d-0001-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: risk_id

		annotation SummarizationSetBy = User

	column drillthrough_risk_id
		dataType: string
		lineageTag: aa1b2c3d-0001-4000-8000-000000000004
		summarizeBy: none
		sourceColumn: drillthrough_risk_id

		annotation SummarizationSetBy = User

	column update_date
		dataType: dateTime
		formatString: MMM d
		lineageTag: aa1b2c3d-0001-4000-8000-000000000005
		summarizeBy: none
		sourceColumn: update_date

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	column author
		dataType: string
		lineageTag: aa1b2c3d-0001-4000-8000-000000000006
		summarizeBy: none
		sourceColumn: author

		annotation SummarizationSetBy = User

	column note
		dataType: string
		lineageTag: aa1b2c3d-0001-4000-8000-000000000007
		summarizeBy: none
		sourceColumn: note

		annotation SummarizationSetBy = User

	column updated_status
		dataType: string
		lineageTag: aa1b2c3d-0001-4000-8000-000000000008
		summarizeBy: none
		sourceColumn: updated_status

		annotation SummarizationSetBy = User

	column probability_at_update
		dataType: int64
		formatString: 0
		lineageTag: aa1b2c3d-0001-4000-8000-000000000009
		summarizeBy: none
		sourceColumn: probability_at_update

		annotation SummarizationSetBy = User

	column cost_impact_at_update
		dataType: int64
		formatString: 0
		lineageTag: aa1b2c3d-0001-4000-8000-00000000000a
		summarizeBy: none
		sourceColumn: cost_impact_at_update

		annotation SummarizationSetBy = User

	column schedule_impact_at_update
		dataType: int64
		formatString: 0
		lineageTag: aa1b2c3d-0001-4000-8000-00000000000b
		summarizeBy: none
		sourceColumn: schedule_impact_at_update

		annotation SummarizationSetBy = User

	column related_risk_level = LOOKUPVALUE(Risk_Register[risk_level], Risk_Register[risk_id], Risk_Updates_AsCurrent[risk_id])
		dataType: string
		isHidden
		lineageTag: aa1b2c3d-0001-4000-8000-00000000000c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Risk_Updates_AsCurrent = m
		mode: import
		source =
				let
				    Updates = Risk_Updates,
				    AddSelf = Table.AddColumn(Updates, "drillthrough_risk_id", each [risk_id], type text),
				    KeepCols = Table.SelectColumns(AddSelf, {"update_id", "risk_id", "drillthrough_risk_id", "update_date", "author", "note", "updated_status", "probability_at_update", "cost_impact_at_update", "schedule_impact_at_update"})
				in
				    KeepCols

	annotation PBI_ResultType = Table

